# Default values for zeebe-simple-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

global:
  zeebe:
    host: zeebe-gateway
    port: 26500

image:
  repository: camunda/zeebe-simple-monitor
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0
  env:
    - name: spring.datasource.url
      value: jdbc:postgresql://postgres-dev:5432/zeebe-monitor
    - name: spring.datasource.driverClassName
      value: org.postgresql.Driver
    - name: spring.jpa.database-platform
      value: org.hibernate.dialect.PostgreSQLDialect

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "simple-monitor"

labels: {}

# Check for the presence of zeebe (to do: add initContainer for postgresql)
initContainers:
  - name: init-zeebe
    image: busybox
    command: ['/bin/sh']
    args: ['-c', 'until (printf "GET /ready HTTP/1.1\r\nHost: $ZEEBE_HOST\r\n\r\n";) | nc $ZEEBE_HOST $ZEEBE_PORT; do echo waiting for zeebe; sleep 2; done']

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 8082

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #requests:
  #  cpu: 250m
  #  memory: 512Mi
  #limits:
  #  cpu: 250m
  #  memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80