apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeebe-simple-monitor.fullname" . }}
  labels:
    app: {{ include "zeebe-simple-monitor.fullname" . }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "zeebe-simple-monitor.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http